import requests
import time
import csv
import random
import regex as re
import concurrent.futures

from bs4 import BeautifulSoup

# Global header for use in web request operation
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

MAX_THREADS = 10 # Number of threads to be used

# Function for extracting the movie data. It receives a link extracted from a soup object -- the main page of IMDB's Top 100 Movies -- 
# and scraps the info from them using html tags with BeautifulSoup. Then it creatres a .csv file with extracted data.
def extract_movie_details(movie_link):
    response = BeautifulSoup(requests.get(movie_link, headers=headers).content, 'html.parser')
    movie_soup = response

    if movie_soup is not None:
        title = None 
        data = None 


        movie_data = movie_soup.find('div', attrs={'class':'sc-e226b0e3-3 jJsEuz'})
        if movie_data is not None: 
            title = movie_data.find('h1').get_text()
            date = movie_data.find('a', attrs={'class':'ipc-link ipc-link--baseAlt ipc-link--inherit-color'}).get_text()
            rating = movie_data.find('span', attrs={'class': 'sc-bde20123-1 iZlgcd'}).get_text() if movie_data.find('span', attrs={'class': 'sc-bde20123-1 iZlgcd'}) else None
            

            with open('./movies.csv', mode='a') as f:
              movie_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
              if all([title, date, rating]):
                print(title, date, rating)
                movie_writer.writerow([title, date, rating])
                

# Function for extracting the individual links of each movie from the main list. It receives a soup object -- an Object generated by BeautifulSoup -- 
# and extracts the link of each individual movie's page.
def extract_movies(soup):
    movies_table = soup.find_all('a', href=True)
    titles = re.findall(r'/title/\w+', str(movies_table)) # Regex command to find all strings with characters '/title/' in them, 
    #the w+ command shows the following characters of the referred string
    movie_links = ['https://imdb.com' + title for title in titles] # Creating complete link by concatenating the string 'https://imdb.com' with the '/title/...' generated by the instruction above
    for i in range(len(movie_links)//2):
        if movie_links[i] == movie_links[i+1]:
            movie_links.remove(movie_links[i+1]) # Removing repeated strings/links

    threads = min(MAX_THREADS, len(movie_links)) # Generating threads to be used on the processing of the insructions
    with concurrent.futures.ThreadPoolExecutor(max_workers=threads) as executor:
        executor.map(extract_movie_details, movie_links)


    


def main():
    start_time = time.time() # Starting timer

    # IMDB Most Popular Movies - 100 movies
    popular_movies_url = 'https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm'
    response = requests.get(popular_movies_url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    # Main function to extract the 100 movies from IMDB Most Popular Movies
    extract_movies(soup)

    end_time = time.time() # Finishing timer
    print("Total time taken: ", end_time - start_time)


if __name__ == '__main__':
    main()
